module.exports = function(sequelize, DataType){
  return sequelize.define("task", {
    // id: Sequalize.INTEGER, do not need, id generated by Sequalize
    body: DataType.STRING,
    completed: DataType.BOOLEAN,
    listID: DataType.INTEGER
  });
}
