module.exports = function(sequelize, Sequelize){
  return sequelize.define("task", {
    // id: Sequalize.INTEGER, do not need, id generated by Sequalize
    body: Sequalize.STRING,
    completed: Sequalize.BOOLEAN,
    listID: Sequalize.INTEGER
  });
}
