module.exports = function(sequelize, Sequelize){
  return sequelize.define("task", {
    body: Sequelize.STRING,
    completed: Sequelize.BOOLEAN
  });
}
// Remember an id column will automatically be generated by sequelize
